apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorlink-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yorlink-frontend
  template:
    metadata:
      labels:
        app: yorlink-frontend
    spec:
      containers:
        - name: frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: yorlink-frontend
  ports:
    - protocol: TCP
      port: 80       # internal port
      targetPort: 80 # container port
  type: ClusterIP